### ISSUE TITLE
SecurityPaper-web

### ISSUE THREAD

**Issue by lifesogood** [SecurityPaper/SecurityPaper-web#11]
https://github.com/sdlchina/sdlchina-web/issues/42
感谢提供建议，请新建一个issues提交你的ID和一句话介绍，加上头像200*200px

上面是之前的 sdlchina/sdlchina-web 现在已经迁移了，没法回复，所以发在这里

ID:
穿过岁月不老

一句话介绍：
人生就像蜡烛 ，站不正必然泪多命短 ！

头像链接：
https://avatars1.githubusercontent.com/u/20538608?s=400&u=0b755ad489f1f55ca1ac6ff77667ee734bc72016&v=4

**Comment by MSG-maniac** [comment]
收到

**Comment by MSG-maniac** [comment]
#
